"""Replace insider_transactions with correct L-4b schema.

Revision ID: 032
Revises: 031
Create Date: 2026-06-06

WHY THIS MIGRATION EXISTS:

Migration 030 used ``CREATE TABLE IF NOT EXISTS insider_transactions`` which
silently no-op'd in every environment where the table was already present from
migration 001 (created via the EODHD Fundamentals blob endpoint with a
completely different schema: ``owner_name``, ``owner_title``,
``acquired_disposed``, ``total_shares_owned``, ``transaction_code`` columns).

As a result:
  * The ``net_value_usd`` column introduced by migration 030's DDL was never
    actually created.
  * Every execution of ``rollup_insider_90d.run_insider_rollup_once`` failed
    with ``column "net_value_usd" does not exist``.
  * The ``insider_net_buy_90d`` screener metric (INSIDER 90D) is always NULL.
  * ``InsiderTransactionsConsumer`` inserts via ``uq_insider_transactions_natural_key``
    which also didn't exist on the legacy table — so inserts were producing
    errors or rolling back silently.

FIX STRATEGY:
  1. DROP TABLE … CASCADE the old broken table. Existing rows are low-fidelity
     stub data from the Fundamentals blob endpoint — not the per-transaction
     EODHD feed. No data worth preserving; the InsiderTransactionsConsumer will
     repopulate from the next S2 fetch cycle.
  2. CREATE TABLE with the full correct L-4b schema from migration 030's
     intended DDL (which was never applied).
  3. Recreate the composite index.

Downgrade: drop the L-4b table and bring back the legacy 001-era schema so
the DB is at least consistent (though no data is restored — this is dev-only).

FORWARD COMPAT (R11):
  The L-4b table schema adds ``net_value_usd`` and ``source`` compared to the
  legacy 001 schema. No existing code reads the old columns (``owner_name``,
  ``acquired_disposed``, etc.) — those fields were only ever accessed by the
  old FundamentalsConsumer which already ignores this table.

IDEMPOTENCY:
  Uses ``DROP TABLE IF EXISTS … CASCADE`` and ``CREATE TABLE`` (not IF NOT
  EXISTS — we want a hard failure if the table somehow already exists with the
  correct schema, so a re-run is detected rather than silently ignored).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "032"
down_revision = "031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Drop the old broken insider_transactions table and recreate with L-4b schema."""
    # ── 1. Drop the old table (and anything that FKs to it) ─────────────────
    # The legacy 001-era table has no FK referencing columns that matter for
    # other tables — CASCADE is precautionary.
    # We do NOT use ``IF EXISTS`` intentionally: if the table is missing here
    # something unexpected happened and we should surface it immediately.
    op.execute("DROP TABLE IF EXISTS insider_transactions CASCADE")

    # ── 2. Recreate with the correct L-4b schema ────────────────────────────
    # Matches InsiderTransactionModel.__table_args__ exactly.  All types use
    # TIMESTAMPTZ (not TIMESTAMP) to guarantee UTC storage (R07).
    #
    # Column notes:
    #   id               — UUIDv7 generated by the consumer; not gen_random_uuid()
    #   filer_name       — ownerName/filerName from EODHD payload
    #   transaction_type — normalised to BUY/SELL/GIFT/OTHER via _TYPE_MAP
    #   net_value_usd    — shares * price, sign-flipped for SELL/GIFT; NULL if price absent
    #   source           — always 'EODHD' for now; VARCHAR(32) for future adapters
    #   ingested_at      — server-side UTC default (explicit AT TIME ZONE 'utc')
    op.execute(
        """
        CREATE TABLE insider_transactions (
            id                UUID          NOT NULL PRIMARY KEY,
            instrument_id     UUID          NOT NULL
                              REFERENCES instruments (id) ON DELETE CASCADE,
            filer_name        VARCHAR(255)  NOT NULL,
            filer_title       VARCHAR(255)  NULL,
            transaction_date  DATE          NOT NULL,
            transaction_type  VARCHAR(16)   NOT NULL,
            shares            NUMERIC(20,4) NOT NULL,
            price_per_share   NUMERIC(20,4) NULL,
            net_value_usd     NUMERIC(20,2) NULL,
            source            VARCHAR(32)   NOT NULL DEFAULT 'EODHD',
            ingested_at       TIMESTAMPTZ   NOT NULL
                              DEFAULT (now() AT TIME ZONE 'utc'),
            CONSTRAINT ck_insider_transactions_type
                CHECK (transaction_type IN ('BUY', 'SELL', 'GIFT', 'OTHER')),
            CONSTRAINT uq_insider_transactions_natural_key
                UNIQUE (instrument_id, filer_name, transaction_date, transaction_type, shares)
        )
        """,
    )

    # ── 3. Composite index — supports both the rollup window query and the
    #       per-instrument detail API (sorted by date desc). ──────────────────
    op.execute(
        """
        CREATE INDEX ix_insider_transactions_instrument_date
        ON insider_transactions (instrument_id, transaction_date DESC)
        """,
    )


def downgrade() -> None:
    """Drop the L-4b table and restore the legacy 001-era schema (without data)."""
    # Drop the L-4b table.
    op.execute("DROP TABLE IF EXISTS insider_transactions CASCADE")

    # Recreate the legacy 001-era table so the DB is structurally consistent
    # when downgrading back to before 032. This schema mirrors what
    # migration 001 originally created via the Fundamentals blob endpoint path.
    op.execute(
        """
        CREATE TABLE insider_transactions (
            id                UUID                     NOT NULL PRIMARY KEY
                              DEFAULT gen_random_uuid(),
            instrument_id     UUID                     NOT NULL
                              REFERENCES instruments (id) ON DELETE CASCADE,
            owner_name        VARCHAR(255)             NOT NULL,
            owner_title       VARCHAR(255)             NULL,
            transaction_date  DATE                     NOT NULL,
            transaction_code  VARCHAR(16)              NULL,
            shares            NUMERIC(20,4)            NULL,
            price_per_share   NUMERIC(20,4)            NULL,
            acquired_disposed VARCHAR(1)               NULL,
            total_shares_owned NUMERIC(20,4)           NULL,
            ingested_at       TIMESTAMPTZ              NOT NULL DEFAULT now()
        )
        """,
    )

    # Re-add a basic index matching what would have existed on the legacy table.
    op.execute(
        sa.text(
            "CREATE INDEX ix_insider_transactions_instrument_date "
            "ON insider_transactions (instrument_id, transaction_date DESC)",
        ),
    )
