"""Unit tests for CanonicalEntityRepository.create_or_get (PLAN-0076 Wave A-1).

DEF-014 / BP-384: ``persist_enrichment`` previously used ``find_exact → create``
which is racy: two concurrent workers can both observe ``existing is None`` and
both INSERT.  Migration 0026 adds a UNIQUE INDEX on ``lower(canonical_name)``,
and ``create_or_get`` issues an atomic ON CONFLICT INSERT that either creates
the row or returns the conflicting existing row.

These tests use a mocked ``AsyncSession`` (no real DB) — the migration-level
acceptance test (``alembic upgrade head`` then duplicate INSERT raises
UniqueViolation) is covered by the integration suite under ``services/
intelligence-migrations/tests/`` and is intentionally out-of-scope here so the
unit suite runs without Postgres.

Coverage:
  - test_create_or_get_new_entity        — happy path: INSERT RETURNING fires.
  - test_create_or_get_existing_entity   — ON CONFLICT path: re-SELECT by name.
  - test_create_or_get_case_insensitive  — case-folding handled by lower(...).
  - test_concurrent_create_or_get        — asyncio.gather of 5 calls converges
                                            to the same entity_id (mocked).
"""

from __future__ import annotations

import asyncio
import json
from unittest.mock import AsyncMock, MagicMock
from uuid import UUID

import pytest
from knowledge_graph.infrastructure.intelligence_db.repositories.canonical_entity import (
    CanonicalEntityRepository,
)

pytestmark = pytest.mark.unit


# Fixed UUIDs so assertions read clearly.  Real entity_ids are generated by the
# DB column default (``gen_random_uuid()``); the tests just need stable values.
_NEW_ENTITY_ID = UUID("01234567-89ab-7def-8012-aaaaaaaaaaaa")
_EXISTING_ENTITY_ID = UUID("01234567-89ab-7def-8012-bbbbbbbbbbbb")


def _make_result_with_row(row: tuple | None) -> MagicMock:
    """Build a MagicMock that mimics a SQLAlchemy ``Result`` with one row."""
    result = MagicMock()
    result.fetchone.return_value = row
    return result


class TestCreateOrGetNewEntity:
    """When the INSERT succeeds (no conflict), return (new_id, True)."""

    async def test_returns_new_entity_id_with_was_created_true(self) -> None:
        # First execute() call = INSERT ... RETURNING entity_id (success path).
        session = AsyncMock()
        session.execute = AsyncMock(return_value=_make_result_with_row((_NEW_ENTITY_ID,)))

        repo = CanonicalEntityRepository(session)
        entity_id, was_created = await repo.create_or_get(
            canonical_name="Apple Inc.",
            entity_type="company",
            ticker="AAPL",
        )

        assert entity_id == _NEW_ENTITY_ID
        assert was_created is True
        # Exactly one DB round-trip — no follow-up SELECT needed when INSERT wins.
        assert session.execute.await_count == 1
        # Verify the INSERT carried the partial-index-aware ON CONFLICT clause.
        # PLAN-0076 QA fix: the partial unique index added by migration 0026
        # excludes ``entity_type='financial_instrument'`` so the ON CONFLICT
        # specifier MUST repeat that predicate verbatim or Postgres refuses
        # the inference.  We assert both halves so a regression that drops
        # the WHERE clause OR drops the conflict target fires this test.
        call_args = session.execute.call_args_list[0]
        sql_text = str(call_args.args[0])
        assert (
            "ON CONFLICT (lower(canonical_name))" in sql_text
        ), f"Expected ON CONFLICT (lower(canonical_name)) target; got SQL:\n{sql_text}"
        assert (
            "WHERE entity_type != 'financial_instrument'" in sql_text
        ), f"Expected partial-index predicate in ON CONFLICT specifier; got SQL:\n{sql_text}"
        assert "DO NOTHING" in sql_text, f"Expected DO NOTHING; got SQL:\n{sql_text}"
        params = call_args.args[1]
        assert params["canonical_name"] == "Apple Inc."
        assert params["entity_type"] == "company"
        assert params["ticker"] == "AAPL"

    async def test_passes_explicit_entity_id_through(self) -> None:
        """Caller-supplied entity_id is propagated and the entity_id INSERT path is taken."""
        session = AsyncMock()
        session.execute = AsyncMock(return_value=_make_result_with_row((_NEW_ENTITY_ID,)))

        repo = CanonicalEntityRepository(session)
        entity_id, was_created = await repo.create_or_get(
            canonical_name="Apple Inc.",
            entity_type="company",
            entity_id=_NEW_ENTITY_ID,
        )

        assert entity_id == _NEW_ENTITY_ID
        assert was_created is True
        params = session.execute.call_args_list[0].args[1]
        # Caller-supplied entity_id is bound to the parameter.
        assert params.get("entity_id") == str(_NEW_ENTITY_ID)


class TestCreateOrGetExistingEntity:
    """When ON CONFLICT fires, fall back to SELECT and return (existing_id, False)."""

    async def test_returns_existing_entity_id_with_was_created_false(self) -> None:
        # First execute = INSERT (conflict, no RETURNING row).
        # Second execute = SELECT by lower(canonical_name) — returns existing row.
        session = AsyncMock()
        session.execute = AsyncMock(
            side_effect=[
                _make_result_with_row(None),  # INSERT conflict
                _make_result_with_row((_EXISTING_ENTITY_ID,)),  # SELECT existing
            ],
        )

        repo = CanonicalEntityRepository(session)
        entity_id, was_created = await repo.create_or_get(
            canonical_name="Apple Inc.",
            entity_type="company",
        )

        assert entity_id == _EXISTING_ENTITY_ID
        assert was_created is False
        # Two round-trips: INSERT (conflict) + SELECT (recovery).
        assert session.execute.await_count == 2
        # Second call MUST be the recovery SELECT keyed on lower(canonical_name).
        select_sql = str(session.execute.call_args_list[1].args[0])
        assert (
            "lower(canonical_name) = lower(:canonical_name)" in select_sql
        ), f"Expected case-insensitive SELECT recovery; got:\n{select_sql}"

    async def test_raises_when_conflict_but_select_finds_nothing(self) -> None:
        """If ON CONFLICT fired but the existing row vanished (concurrent DELETE),
        raise rather than silently returning a wrong/None id.
        """
        session = AsyncMock()
        session.execute = AsyncMock(
            side_effect=[
                _make_result_with_row(None),  # INSERT conflict
                _make_result_with_row(None),  # SELECT — nothing found (race)
            ],
        )

        repo = CanonicalEntityRepository(session)
        with pytest.raises(RuntimeError, match="ON CONFLICT fired"):
            await repo.create_or_get(canonical_name="Ghost Co.", entity_type="company")


class TestCreateOrGetCaseInsensitive:
    """``Apple Inc.`` and ``apple inc.`` map to the same row via lower(canonical_name)."""

    async def test_case_insensitive_dedup_uses_lower_function(self) -> None:
        # Caller passes "apple inc." (lowercase) — ON CONFLICT fires because
        # "Apple Inc." (mixed case) already exists in the index.  The recovery
        # SELECT uses lower(canonical_name) = lower(:canonical_name) so the
        # case difference is collapsed and we still find the existing row.
        session = AsyncMock()
        session.execute = AsyncMock(
            side_effect=[
                _make_result_with_row(None),  # INSERT conflict on lower-name match
                _make_result_with_row((_EXISTING_ENTITY_ID,)),
            ],
        )

        repo = CanonicalEntityRepository(session)
        entity_id, was_created = await repo.create_or_get(
            canonical_name="apple inc.",
            entity_type="company",
        )

        assert entity_id == _EXISTING_ENTITY_ID
        assert was_created is False
        # Verify the SELECT bound the lowercase variant — the lower(...) wrapper
        # in the SQL guarantees the index path is hit regardless of caller case.
        select_params = session.execute.call_args_list[1].args[1]
        assert select_params["canonical_name"] == "apple inc."


class TestConcurrentCreateOrGet:
    """asyncio.gather of 5 concurrent calls all converge to the same entity_id.

    We mock at the infrastructure level — only the FIRST call's INSERT wins
    (returns _NEW_ENTITY_ID).  The other four hit ON CONFLICT and recover via
    SELECT, all returning the same _NEW_ENTITY_ID.  This simulates the
    production race the UNIQUE INDEX is designed to catch.
    """

    async def test_five_concurrent_callers_converge_to_one_entity_id(self) -> None:
        # Each call needs its own session (async session lifetime is per-call
        # in production).  The first session's INSERT wins; the other four see
        # the ON CONFLICT path.
        winning_session = AsyncMock()
        winning_session.execute = AsyncMock(return_value=_make_result_with_row((_NEW_ENTITY_ID,)))

        def _make_loser_session() -> AsyncMock:
            losing_session = AsyncMock()
            losing_session.execute = AsyncMock(
                side_effect=[
                    _make_result_with_row(None),  # INSERT conflict
                    _make_result_with_row((_NEW_ENTITY_ID,)),  # SELECT recovery
                ],
            )
            return losing_session

        sessions = [winning_session] + [_make_loser_session() for _ in range(4)]
        repos = [CanonicalEntityRepository(s) for s in sessions]

        # asyncio.gather — fan out 5 concurrent create_or_get calls.
        results = await asyncio.gather(
            *[r.create_or_get(canonical_name="Apple Inc.", entity_type="company") for r in repos],
        )

        # All five callers see the SAME entity_id (no duplicate row created).
        entity_ids = {r[0] for r in results}
        assert entity_ids == {
            _NEW_ENTITY_ID
        }, f"Concurrent callers diverged: {entity_ids}.  Expected exactly one entity_id."
        # Exactly one caller reports was_created=True; the rest report False.
        was_created_flags = [r[1] for r in results]
        assert was_created_flags.count(True) == 1, f"Expected exactly one winner, got was_created={was_created_flags}"
        assert was_created_flags.count(False) == 4


class TestPatchMetadata:
    """``patch_metadata`` shallow-merges into ``canonical_entities.metadata`` (JSONB).

    BP-637 / PLAN-0103 W19: FundamentalsRefreshWorker calls this to mirror the
    EODHD GICS sector + industry into ``metadata``. The method was missing from
    the repository, so the worker crashed every cycle with ``AttributeError:
    'CanonicalEntityRepository' object has no attribute 'patch_metadata'``,
    aborting the run before any embedding write — leaving the
    ``fundamentals_ohlcv`` embedding view empty (0 rows embedded).
    """

    async def test_issues_jsonb_merge_update(self) -> None:
        session = AsyncMock()
        session.execute = AsyncMock()

        repo = CanonicalEntityRepository(session)
        await repo.patch_metadata(_EXISTING_ENTITY_ID, {"sector": "Technology", "industry": "Software"})

        assert session.execute.await_count == 1
        sql_text = str(session.execute.call_args_list[0].args[0])
        # JSONB shallow-merge — preserves keys not present in the patch.
        assert (
            "metadata = COALESCE(metadata, '{}'::jsonb) || cast(:patch AS jsonb)" in sql_text
        ), f"Expected JSONB shallow-merge UPDATE; got:\n{sql_text}"
        assert "WHERE entity_id = :entity_id" in sql_text
        params = session.execute.call_args_list[0].args[1]
        assert params["entity_id"] == str(_EXISTING_ENTITY_ID)
        # patch is JSON-serialised so the ``::jsonb`` cast parses it.
        assert json.loads(params["patch"]) == {"sector": "Technology", "industry": "Software"}

    async def test_empty_patch_is_noop(self) -> None:
        """No DB round-trip when the patch is empty (nothing to merge)."""
        session = AsyncMock()
        session.execute = AsyncMock()

        repo = CanonicalEntityRepository(session)
        await repo.patch_metadata(_EXISTING_ENTITY_ID, {})

        session.execute.assert_not_awaited()


class TestRetypeAttemptTracking:
    """Attempt cap for the ``unknown`` re-typing sweep (2026-07-16 follow-up).

    Without a cap a permanently-unclassifiable ``unknown`` row is re-sent to the
    extraction LLM every 30-min cycle forever. ``list_unknown_entities`` now
    excludes rows whose ``metadata->>'retype_attempts'`` has reached the cap, and
    ``record_retype_attempts`` bumps that counter for rows the LLM could not type.
    """

    async def test_list_unknown_entities_filters_on_attempt_cap(self) -> None:
        session = AsyncMock()
        result = MagicMock()
        result.fetchall.return_value = []
        session.execute = AsyncMock(return_value=result)

        repo = CanonicalEntityRepository(session)
        await repo.list_unknown_entities(50, max_attempts=3)

        sql_text = str(session.execute.call_args_list[0].args[0])
        # The cap predicate must be present so capped rows never re-hit the LLM.
        # COALESCE(...,0) keeps never-attempted rows (no metadata key) eligible.
        assert (
            "COALESCE((metadata->>'retype_attempts')::int, 0) < :max_attempts" in sql_text
        ), f"Expected attempt-cap predicate; got SQL:\n{sql_text}"
        params = session.execute.call_args_list[0].args[1]
        assert params["max_attempts"] == 3
        assert params["limit"] == 50

    async def test_list_unknown_entities_default_cap_is_three(self) -> None:
        """The repo default mirrors the config default (3) so a caller that omits
        the argument still gets the cap, not an unbounded scan."""
        session = AsyncMock()
        result = MagicMock()
        result.fetchall.return_value = []
        session.execute = AsyncMock(return_value=result)

        repo = CanonicalEntityRepository(session)
        await repo.list_unknown_entities(10)

        params = session.execute.call_args_list[0].args[1]
        assert params["max_attempts"] == 3

    async def test_record_retype_attempts_bumps_counter_and_stamps_time(self) -> None:
        session = AsyncMock()
        session.execute = AsyncMock()

        repo = CanonicalEntityRepository(session)
        await repo.record_retype_attempts([_NEW_ENTITY_ID, _EXISTING_ENTITY_ID])

        assert session.execute.await_count == 1
        sql_text = str(session.execute.call_args_list[0].args[0])
        # Monotonic increment of the JSONB counter + last-attempt timestamp.
        assert "'retype_attempts', COALESCE((metadata->>'retype_attempts')::int, 0) + 1" in sql_text
        assert "'retype_last_attempt_at', :now" in sql_text
        # Guarded on entity_type='unknown' so a concurrently-typed row is untouched.
        assert "AND entity_type = 'unknown'" in sql_text
        params = session.execute.call_args_list[0].args[1]
        assert params["ids"] == [str(_NEW_ENTITY_ID), str(_EXISTING_ENTITY_ID)]
        # Timestamp is an ISO-8601 UTC string (RULES.md #7 — no naive datetimes).
        assert isinstance(params["now"], str)
        assert params["now"].endswith("+00:00") or params["now"].endswith("Z")

    async def test_record_retype_attempts_empty_list_is_noop(self) -> None:
        """No DB round-trip when there are no unresolved rows to bump."""
        session = AsyncMock()
        session.execute = AsyncMock()

        repo = CanonicalEntityRepository(session)
        await repo.record_retype_attempts([])

        session.execute.assert_not_awaited()


class TestFindFinancialInstrumentForCompany:
    """Cross-type ORG->FI lookup used by the provisional-promotion dedup guard.

    Regression (2026-07 KG, commit a6bf179be): a ticker-less ``organization``
    mention binds ``:ticker`` as ``None``.  Because the bind appears only in
    ``:ticker IS NOT NULL`` / ``UPPER(:ticker)`` positions, asyncpg cannot infer
    the parameter type and raised ``AmbiguousParameterError`` — aborting
    provisional enrichment for ~800 ticker-less orgs every 2h.  The fix casts the
    bind (``CAST(:ticker AS text)``); these tests pin that the SQL carries the
    cast and that a null-ticker lookup executes without raising.
    """

    async def test_null_ticker_lookup_does_not_raise_and_binds_none(self) -> None:
        """A ticker-less org (name-only match) must execute cleanly with ticker=None."""
        session = AsyncMock()
        # No FI matches -> fetchone returns None -> function returns None.
        session.execute = AsyncMock(return_value=_make_result_with_row(None))

        repo = CanonicalEntityRepository(session)
        result = await repo.find_financial_instrument_for_company(ticker=None, canonical_name="Some Private Company")

        assert result is None
        # The None ticker is passed straight through as a bound param (never
        # inlined) so the CAST is what makes the NULL bind legal.
        params = session.execute.call_args_list[0].args[1]
        assert params["ticker"] is None
        assert params["canonical_name"] == "Some Private Company"

    async def test_ticker_bind_is_cast_to_text_in_sql(self) -> None:
        """Every ``:ticker`` occurrence must be wrapped in ``CAST(:ticker AS text)``."""
        session = AsyncMock()
        session.execute = AsyncMock(return_value=_make_result_with_row(None))

        repo = CanonicalEntityRepository(session)
        await repo.find_financial_instrument_for_company(ticker=None, canonical_name="X")

        sql_text = str(session.execute.call_args_list[0].args[0])
        assert "CAST(:ticker AS text)" in sql_text
        # No bare ``:ticker`` left un-cast (would re-introduce the ambiguity).
        assert ":ticker IS NOT NULL" not in sql_text
        assert "UPPER(:ticker)" not in sql_text

    async def test_returns_matching_fi_entity_id(self) -> None:
        """When an FI matches by ticker, its entity_id is returned as a UUID."""
        session = AsyncMock()
        session.execute = AsyncMock(return_value=_make_result_with_row((_EXISTING_ENTITY_ID,)))

        repo = CanonicalEntityRepository(session)
        result = await repo.find_financial_instrument_for_company(ticker="AAPL", canonical_name="Apple")

        assert result == _EXISTING_ENTITY_ID
        params = session.execute.call_args_list[0].args[1]
        assert params["ticker"] == "AAPL"
