"""Backfill alert.title for rows with NULL or humanised-enum fallback titles.

PLAN-0053 T-A-1-07.

Existing rows fall into three categories:
  1. ``title IS NULL``                 — pre-PLAN-0049 alerts.
  2. ``title = 'Graph Change Alert'``  — generated by the old fallback ladder.
  3. ``title = 'Contradiction Alert'`` — same.
  4. ``title = 'Signal Alert'``        — same.

The new per-type template engine (T-A-1-06) writes proper titles for all
NEW alerts, but historical rows still display useless titles on the
dashboard. This migration rewrites them in place using the same templates
as the application layer, so old alerts become readable too.

Idempotency: the WHERE clause filters only NULL / known-generic strings,
so re-running is a no-op.
"""

from __future__ import annotations

from alembic import op

# revision identifiers
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Apply per-AlertType templates. NULL-safe via COALESCE(ticker, entity_name).
    # The CASE arms mirror _compose_alert_title() in alert_fanout.py exactly.
    #
    # WHY guarded by WHERE: only touch rows that need fixing. Rows with a
    # well-composed title (e.g. ``"AAPL: Bullish guidance"``) must NOT be
    # rewritten — those have already been processed by the new code path.
    op.execute(
        """
        UPDATE alerts SET title = (
          CASE
            -- SIGNAL with meaningful signal_label: keep existing logic.
            WHEN alert_type = 'SIGNAL'
                 AND signal_label IS NOT NULL
                 AND signal_label NOT LIKE '%signal'  -- exclude "LOW signal" etc.
                 AND COALESCE(ticker, entity_name) IS NOT NULL
              THEN COALESCE(ticker, entity_name) || ': ' || signal_label

            WHEN alert_type = 'SIGNAL'
                 AND signal_label IS NOT NULL
                 AND signal_label NOT LIKE '%signal'
              THEN signal_label

            WHEN alert_type = 'SIGNAL'
                 AND COALESCE(ticker, entity_name) IS NOT NULL
              THEN COALESCE(ticker, entity_name) || ': Signal'

            WHEN alert_type = 'SIGNAL'
              THEN 'Signal detected'

            -- GRAPH_CHANGE: fixed template, no NLP context expected.
            WHEN alert_type = 'GRAPH_CHANGE'
                 AND COALESCE(ticker, entity_name) IS NOT NULL
              THEN COALESCE(ticker, entity_name) || ': Graph pattern change'
            WHEN alert_type = 'GRAPH_CHANGE'
              THEN 'Graph pattern change'

            -- CONTRADICTION: fixed template.
            WHEN alert_type = 'CONTRADICTION'
                 AND COALESCE(ticker, entity_name) IS NOT NULL
              THEN COALESCE(ticker, entity_name) || ': Conflicting signals'
            WHEN alert_type = 'CONTRADICTION'
              THEN 'Conflicting signals'

            ELSE COALESCE(title, 'Alert')
          END
        )
        WHERE title IS NULL
           OR title = 'Graph Change Alert'
           OR title = 'Contradiction Alert'
           OR title = 'Signal Alert'
           OR title ~ '^[A-Z][a-z]+ [A-Z][a-z]+ alert$'
        """
    )


def downgrade() -> None:
    # Backfill is a one-way data fix; we cannot recover the original NULLs
    # without a snapshot. Downgrade is a no-op (data already on disk is the
    # corrected form). Schema is unchanged so this is safe.
    pass
