"""Guard test: ChunkModel must NOT declare ``tsv_english`` / ``tsv_simple``.

BP-NEW1 — those columns are GENERATED by Postgres (migration 0017) and any
attempt to INSERT or UPDATE a value for them (even ``None``) raises
``cannot insert into column "tsv_english" because it is a GENERATED column``.
Declaring them on the ORM would defeat that protection on the SQLAlchemy side
and silently break every chunk write the moment the model class is reused for
a write path. This test pins the ORM shape so that any future "innocent"
addition is caught at unit-test time.

PLAN-0063 W5-2 / FR-T1-2.
"""

from __future__ import annotations

import pytest
from nlp_pipeline.infrastructure.nlp_db.models import ChunkModel

pytestmark = pytest.mark.unit


def test_chunk_model_does_not_declare_tsv_columns() -> None:
    """``tsv_english`` and ``tsv_simple`` must stay out of ChunkModel (BP-NEW1)."""
    declared = {c.name for c in ChunkModel.__mapper__.columns}
    assert (
        "tsv_english" not in declared
    ), "tsv_english is a GENERATED column — declaring it on the ORM breaks INSERT (BP-NEW1)"
    assert (
        "tsv_simple" not in declared
    ), "tsv_simple is a GENERATED column — declaring it on the ORM breaks INSERT (BP-NEW1)"


def test_chunk_model_declares_denorm_columns() -> None:
    """``title_denorm`` and ``section_heading_denorm`` MUST be ORM-writeable."""
    declared = {c.name for c in ChunkModel.__mapper__.columns}
    assert "title_denorm" in declared, "title_denorm must be ORM-declared so the chunk-writer can populate it"
    assert (
        "section_heading_denorm" in declared
    ), "section_heading_denorm must be ORM-declared so the chunk-writer can populate it"
