"""Minimal type stubs for confluent_kafka v2.4.x.

These stubs cover only the symbols used by libs/messaging.  They are
intentionally incomplete — new stubs should be added here as more of the
confluent_kafka API surface is consumed.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

class KafkaError:
    """Represents a Kafka error code."""

    _PARTITION_EOF: int
    _ALL_BROKERS_DOWN: int
    _UNKNOWN_TOPIC: int

    def code(self) -> int: ...
    def str(self) -> str: ...
    def fatal(self) -> bool: ...
    def retriable(self) -> bool: ...
    def __bool__(self) -> bool: ...

class KafkaException(Exception):  # noqa: N818
    def __init__(self, error: KafkaError | None = None, *args: Any) -> None: ...
    args: tuple[Any, ...]  # type: ignore[override]

class Message:
    """A consumed Kafka message."""

    def topic(self) -> str: ...
    def partition(self) -> int: ...
    def offset(self) -> int: ...
    def key(self) -> bytes | str | None: ...
    def value(self) -> bytes | None: ...
    def error(self) -> KafkaError | None: ...
    def headers(self) -> list[tuple[str, bytes]] | None: ...
    def timestamp(self) -> tuple[int, int]: ...
    def latency(self) -> float | None: ...

class Consumer:
    """High-level Kafka consumer."""

    def __init__(self, config: dict[str, Any]) -> None: ...
    def subscribe(
        self,
        topics: list[str],
        on_assign: Callable[..., None] | None = None,
        on_revoke: Callable[..., None] | None = None,
    ) -> None: ...
    def poll(self, timeout: float = -1.0) -> Message | None: ...
    def commit(
        self,
        message: Message | None = None,
        offsets: list[Any] | None = None,
        asynchronous: bool = True,
    ) -> None: ...
    def close(self) -> None: ...
    def assignment(self) -> list[Any]: ...
    def position(self, partitions: list[Any]) -> list[Any]: ...
    def pause(self, partitions: list[Any]) -> None: ...
    def resume(self, partitions: list[Any]) -> None: ...
    def get_watermark_offsets(
        self,
        partition: Any,
        timeout: float = -1.0,
        cached: bool = False,
    ) -> tuple[int, int]: ...

class TopicPartition:
    """Represents a Kafka topic partition with optional offset."""

    topic: str
    partition: int
    offset: int

    def __init__(
        self,
        topic: str,
        partition: int = -1,
        offset: int = -1001,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Producer:
    """Low-level Kafka producer."""

    def __init__(self, config: dict[str, Any]) -> None: ...
    def produce(
        self,
        topic: str,
        value: bytes | str | None = None,
        key: bytes | str | None = None,
        headers: dict[str, bytes] | list[tuple[str, bytes]] | None = None,
        on_delivery: Callable[[KafkaError | None, Message], None] | None = None,
    ) -> None: ...
    def flush(self, timeout: float = -1.0) -> int: ...
    def poll(self, timeout: float = 0.0) -> int: ...

class SerializingProducer:
    """Confluent SerializingProducer wrapping an Avro/JSON serializer."""

    def __init__(self, config: dict[str, Any]) -> None: ...
    def produce(
        self,
        topic: str,
        value: Any | None = None,
        key: Any | None = None,
        headers: dict[str, bytes] | list[tuple[str, bytes]] | None = None,
        on_delivery: Callable[[KafkaError | None, Message], None] | None = None,
    ) -> None: ...
    def flush(self, timeout: float = -1.0) -> int: ...
    def poll(self, timeout: float = 0.0) -> int: ...

class DeserializingConsumer:
    """Confluent DeserializingConsumer wrapping an Avro/JSON deserializer."""

    def __init__(self, config: dict[str, Any]) -> None: ...
    def subscribe(self, topics: list[str]) -> None: ...
    def poll(self, timeout: float = -1.0) -> Message | None: ...
    def commit(self, message: Message | None = None, asynchronous: bool = True) -> None: ...
    def close(self) -> None: ...
