/**
 * app/layout.tsx — Root layout for the entire worldview-web application
 *
 * WHY THIS EXISTS: Next.js App Router requires a root layout that wraps ALL pages.
 * This layout:
 * 1. Loads IBM Plex fonts (Sans + Mono) from Google Fonts via next/font
 * 2. Sets class="dark" permanently on <html> (Bloomberg Dark theme, ADR-F-04)
 * 3. Provides the TanStack Query client for all child components
 * 4. Sets page metadata (title, description, Open Graph)
 *
 * WHY NOT a client component: Root layout should be a Server Component to
 * avoid hydration issues and enable proper metadata generation.
 * Client-side providers (QueryClient, AuthContext) are added via Providers.tsx.
 *
 * WHO USES IT: Every page in the application.
 * DESIGN REFERENCE: docs/ui/DESIGN_SYSTEM.md §3 Typography
 */

import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { CookieConsentBanner } from "@/components/legal/CookieConsentBanner";

/**
 * IBM Plex Sans — for all UI labels, headings, and prose text
 * WHY IBM Plex Sans: Professional, legible at small sizes, excellent for
 * information-dense displays. Same font family used by IBM's own data tools.
 * variable="--font-sans" maps to tailwind.config.ts fontFamily.sans
 *
 * PLAN-0059 W0 F-VISUAL-NEW-G: dropped weight 300 (font-light) — grep found
 * zero usage across the codebase. Saves ~45 KB on initial font payload.
 * Active weights: 400 (body), 500 (medium UI), 600 (titles), 700 (hero/bold).
 */
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});

/**
 * IBM Plex Mono — for ALL numeric values: prices, percentages, quantities, dates
 * WHY monospace for numbers: Ensures tabular alignment in tables without
 * needing fixed-width column CSS. Bloomberg Terminal and TradingView both use
 * monospace numbers — our target users expect this.
 * ADR-F-15: This is the single highest-impact visual rule in the design system.
 *
 * PLAN-0059 W0 F-VISUAL-NEW-G: dropped weight 600 — mono never uses bold in
 * the codebase (price/data display always at 400 or 500). Saves ~25 KB.
 */
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Worldview",
    default: "Worldview — Institutional Market Intelligence",
  },
  description:
    "Bloomberg-grade market intelligence. AI-native research, entity graphs, news intelligence, prediction markets, and real-time alerts.",
  keywords: [
    "market intelligence",
    "stock research",
    "financial data",
    "entity graph",
    "AI finance",
    "institutional terminal",
  ],
  // PLAN-0059 W0 F-VISUAL-NEW-C / fix F-004 (2026-04-30) — brand identity.
  // SVG icons auto-discovered by Next.js (app/icon.svg, app/apple-icon.svg).
  // Raster icons + OG/Twitter cards live in `public/` (generated by
  // `scripts/generate-brand-assets.mjs`, runs as a `prebuild` hook).
  manifest: "/manifest.webmanifest",
  icons: {
    // Multi-resolution favicons for browsers that prefer raster
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/icon-180.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: ["/favicon.ico"],
  },
  openGraph: {
    type: "website",
    title: "Worldview — Institutional Market Intelligence",
    description: "Bloomberg-grade research without the Bloomberg bill.",
    siteName: "Worldview",
    // PLAN-0059 W0 fix F-004 (2026-04-30): wire OG image so LinkedIn / Slack
    // / Discord render a brand preview when the URL is shared. Generated by
    // scripts/generate-brand-assets.mjs at prebuild time.
    images: [
      { url: "/og-image.png", width: 1200, height: 630, alt: "Worldview — institutional market intelligence" },
      { url: "/og-image-square.png", width: 1200, height: 1200, alt: "Worldview brand mark" },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Worldview — Institutional Market Intelligence",
    description: "Bloomberg-grade research without the Bloomberg bill.",
    // PLAN-0059 W0 fix F-004: Twitter summary_large_image variant.
    images: ["/twitter-card.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // class="dark": permanent dark mode — never changes (ADR-F-04)
    // font variables: injected as CSS custom props so Tailwind font-sans/mono work
    <html
      lang="en"
      className={`dark ${ibmPlexSans.variable} ${ibmPlexMono.variable}`}
      // suppressHydrationWarning: prevents hydration mismatch from class="dark"
      // being set server-side (Next.js SSR) vs client-side
      suppressHydrationWarning
    >
      <body className="min-h-screen bg-background font-sans antialiased">
        {/* Providers wraps all client-side context providers:
            - QueryClientProvider for TanStack Query
            - AuthProvider for OIDC token state
            (These are "use client" components, separated to keep layout as Server Component) */}
        <Providers>{children}</Providers>
        {/* PLAN-0059 I-6: cookie/storage consent banner. Mounted at the root
            so it appears on both authenticated and unauthenticated surfaces.
            Self-hides after the user records a decision. */}
        <CookieConsentBanner />
      </body>
    </html>
  );
}
