/**
 * components/instrument/intelligence/InstrumentBriefSection.tsx
 *
 * WHY THIS EXISTS:
 * Extracted from IntelligenceTab.tsx (was lines 233-285) so the tab orchestrator
 * stays under 400 lines while each concern lives in a focused file.
 *
 * Renders the AI Intelligence Brief from GET /v1/briefings/instrument/{entityId}.
 * The brief is a markdown narrative generated by the LLM pipeline and cached
 * for 30 minutes (staleTime) to avoid hammering the backend during page revisits.
 *
 * WHY staleTime=30min: briefs are generated asynchronously by the intelligence
 * pipeline; they don't change minute-to-minute. 30 minutes trades freshness for
 * fewer API calls while still surfacing same-day updates.
 *
 * WHY retry=2 with retryDelay=10s: brief generation can take 10–30s on cold
 * start. A 503 on the first request is normal; the 10s delay gives the worker
 * time to finish without hammering the gateway.
 *
 * DATA SOURCE: GET /v1/briefings/instrument/{entityId} (via S9 gateway)
 *
 * WHO USES IT: components/instrument/IntelligenceTab.tsx
 */

"use client";

import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { createGateway } from "@/lib/gateway";
import { useAuth } from "@/hooks/useAuth";
import { Skeleton } from "@/components/ui/skeleton";
import { MarkdownContent } from "@/components/ui/markdown-content";
import type { BriefingResponse } from "@/types/api";

// WHY 12h threshold (not 24h): a stale brief after 12 hours means the platform
// has not run a new pipeline cycle for this entity since yesterday. That gap
// is worth surfacing; 24h would silently accept day-old briefs.
const BRIEF_STALE_MS = 12 * 60 * 60 * 1000;

// ── Props ─────────────────────────────────────────────────────────────────────

interface InstrumentBriefSectionProps {
  entityId: string;
}

// ── InstrumentBriefSection ────────────────────────────────────────────────────

export function InstrumentBriefSection({ entityId }: InstrumentBriefSectionProps) {
  const { accessToken } = useAuth();
  const { data: brief, isLoading, isError, error } = useQuery<BriefingResponse>({
    queryKey: ["instrument-brief", entityId],
    queryFn: () => createGateway(accessToken).getInstrumentBrief(entityId),
    enabled: !!accessToken && !!entityId,
    staleTime: 30 * 60 * 1000,
    retry: 2,
    retryDelay: 10_000,
  });

  return (
    <section className="p-3">
      <h3 className="mb-2 text-[10px] uppercase tracking-[0.08em] text-muted-foreground">AI Intelligence Brief</h3>
      {isLoading && (
        <div className="space-y-2">
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-2/3" />
        </div>
      )}
      {isError && !isLoading && (
        <div className="rounded-[2px] border border-border/30 bg-card/30 p-3 text-[11px] text-muted-foreground">
          {error instanceof Error && (error.message.includes("503") || error.message.includes("unavailable"))
            ? "Brief generating... check back in a few minutes."
            : "Intelligence brief unavailable."}
        </div>
      )}
      {!isLoading && !isError && brief && (
        <div>
          {Date.now() - new Date(brief.generated_at).getTime() > BRIEF_STALE_MS && (
            <div className="mb-2 flex items-center gap-1">
              <RefreshCw className="h-3 w-3 text-warning" />
              <span className="text-[11px] text-warning">Brief may be outdated</span>
            </div>
          )}
          <MarkdownContent size="compact">{brief.narrative}</MarkdownContent>
          <p className="mt-2 font-mono text-[10px] tabular-nums text-muted-foreground">
            Generated {new Date(brief.generated_at).toISOString().slice(0, 16).replace("T", " ")} UTC
          </p>
        </div>
      )}
      {!isLoading && !isError && !brief && (
        <div className="rounded-[2px] border border-border/30 bg-card/30 p-3 text-[11px] text-muted-foreground">
          No intelligence brief available for this entity yet.
        </div>
      )}
    </section>
  );
}
