"""Worker 13D-1: Definition embedding refresh (PRD §6.7 Block 13D-1 / PRD-0017 §6.5).

Triggered indirectly via consumers (market.instrument.created, market.dataset.fetched)
and also runs as a periodic fallback (quarterly — 90-day schedule).

For ``financial_instrument`` entities: source_text comes from EODHD (already stored).
For all other entity types: source_text is GENERATED by this worker each cycle using
``EntityDescriptionClient`` (gemini-3.1-flash-lite); falls back to a deterministic
template when the API is unavailable or cost cap exceeded.

Change detection: SHA-256(source_text) != source_hash → re-embed.
Uses FallbackChainClient: Ollama → Gemini Flash Lite → NULL + schedule retry.
UPSERT entity_embedding_state WHERE view_type='definition' with
next_refresh_at = now() + 90 days.
"""

from __future__ import annotations

import dataclasses
from datetime import timedelta
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import text as sa_text

from common.time import utc_now  # type: ignore[import-untyped]
from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
    VIEW_DEFINITION,
    sha256_hex,
)
from observability import get_logger  # type: ignore[import-untyped]

if TYPE_CHECKING:
    from ml_clients.description_client import EntityDescriptionClient  # type: ignore[import-untyped]
    from ml_clients.usage_log import LlmUsageLogProtocol
    from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

    from knowledge_graph.infrastructure.llm.fallback_chain import FallbackChainClient

logger = get_logger(__name__)  # type: ignore[no-any-return]

_REFRESH_INTERVAL_DAYS = 90
_DEFAULT_EMBED_MODEL_ID = "nomic-embed-text"
_FINANCIAL_INSTRUMENT = "financial_instrument"

# Maximum texts to send in a single embed() call.  DeepInfra and most providers
# accept batches of several hundred inputs; 200 is a conservative safe ceiling.
_EMBED_CHUNK_SIZE = 200


def _fallback_description(canonical_name: str, entity_type: str) -> str:
    """Deterministic description template — used when LLM is unavailable or cost-capped."""
    return f"{canonical_name} is a {entity_type}."


class DefinitionRefreshWorker:
    """Refreshes definition-view embeddings for entities (Worker 13D-1).

    For ``financial_instrument`` entities the description comes from EODHD data
    already stored as ``source_text``.  For all other entity types the worker
    generates a fresh world-knowledge description each cycle via
    ``description_client`` and falls back to a deterministic template on failure.

    Args:
    ----
        session_factory:    Read/write sessionmaker for intelligence_db.
        llm_client:         FallbackChainClient (embedding path).
        description_client: EntityDescriptionClient for non-company descriptions.
                            If None, ``NullDescriptionAdapter`` is used (always
                            returns None → falls back to deterministic template).

    """

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
        llm_client: FallbackChainClient,
        description_client: EntityDescriptionClient | None = None,
        usage_logger: LlmUsageLogProtocol | None = None,
        embedding_model_id: str = _DEFAULT_EMBED_MODEL_ID,
        batch_limit: int = 0,
        read_session_factory: Any = None,
    ) -> None:
        self._sf = session_factory
        # DEF-034 (Wave B-5): route Phase 1 fetch through the read replica when
        # one is configured; fall back to the write factory so existing tests
        # that pass only ``session_factory`` keep working unchanged.
        self._read_session_factory: Any = read_session_factory if read_session_factory is not None else session_factory
        self._llm = llm_client
        self._embed_model_id = embedding_model_id
        if description_client is None:
            from ml_clients.description_client import NullDescriptionAdapter  # type: ignore[import-untyped]

            self._description_client: EntityDescriptionClient = NullDescriptionAdapter()
        else:
            self._description_client = description_client
        # Inject usage logger into GeminiDescriptionAdapter if present (PLAN-0033 T-D-1-03)
        if usage_logger is not None:
            _adapter = getattr(self._description_client, "_adapter", None)
            if _adapter is not None:
                _adapter._usage_logger = usage_logger
        self._batch_limit = batch_limit

    async def run(self) -> None:
        """Periodic fallback: refresh definition embeddings due for refresh.

        Execution is split into three phases to avoid holding a DB session
        across external I/O (HTTP description generation + ML embedding calls):

        Phase 1 — Read: fetch due rows, generate descriptions, close session.
        Phase 2 — Embed: call embed() ONCE for all changed texts (no session open).
        Phase 3 — Write: upsert all results in a single session + commit.
        """
        from ml_clients.dataclasses import EmbeddingInput  # type: ignore[import-untyped]

        from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
            EntityEmbeddingStateRepository,
        )

        # ── Phase 1: Read ────────────────────────────────────────────────────
        # Fetch all due rows and resolve source texts (including LLM description
        # generation for non-company entities).  Session is released before any
        # embed() calls.
        # DEF-034 (Wave B-5): the SELECT batch uses the read replica factory.
        # Writes in Phase 3 stay on the primary write factory.
        async with self._read_session_factory() as session:
            emb_repo = EntityEmbeddingStateRepository(session)
            due = await emb_repo.get_due_for_refresh(VIEW_DEFINITION, self._batch_limit)
        # Session released here — FOR UPDATE lock released, that is acceptable
        # because this worker runs as a single periodic process.

        if not due:
            logger.info(  # type: ignore[no-any-return]
                "definition_refresh_worker_complete",
                refreshed=0,
                skipped_unchanged=0,
            )
            return

        # ── Phase 2: Process + batch embed ───────────────────────────────────
        # No DB session open during description generation or embedding calls.
        # We first collect ALL entities that need new embeddings, then call
        # embed() ONCE with all texts (chunked by _EMBED_CHUNK_SIZE).
        skipped = 0

        @dataclasses.dataclass
        class _Update:
            entity_id: UUID
            source_text: str
            source_hash: str
            embedding: list[float] | None
            model_id: str | None

        # Rows where hash matches — push next_refresh_at forward, no re-embed.
        unchanged: list[_Update] = []
        # Rows that need fresh embeddings: (entity_id, source_text, source_hash).
        needs_embed: list[tuple[UUID, str, str]] = []

        for row in due:
            entity_id: UUID = row["entity_id"]  # type: ignore[assignment]
            entity_type = str(row.get("entity_type") or "")
            source_text = str(row.get("source_text") or "")

            if entity_type != _FINANCIAL_INSTRUMENT:
                source_text = await self._resolve_non_company_text(entity_id, entity_type, row)
            elif not source_text:
                # ── 2026-06-14 P1 (empty-entity-descriptions RC2) ──────────────
                # Normally a financial_instrument's source_text is the EODHD
                # business description, populated at create-time by the
                # instrument consumer. But ~48 FI entities are crypto/FX/indices
                # (BTC.USD, ETH.USD, GBPUSD, DJI, GSPC, IXIC, …) that EODHD has
                # NO business description for, so source_text IS NULL. Previously
                # the `if not source_text: continue` below skipped them on EVERY
                # cycle forever — they never got a definition embedding.
                #
                # When an FI row has NULL source_text, synthesize a description
                # via the DeepInfra description client (the same path used for
                # non-company entities). This does NOT touch the normal FI path:
                # any FI with a non-empty EODHD description skips this branch.
                #
                # BP-114 guard: _resolve_definition_text_for_null_fi returns ""
                # (not the trivial "X is a financial_instrument." template) when
                # the LLM yields nothing, so the `if not source_text: continue`
                # below skips persisting a degenerate description rather than
                # locking in a useless one for 90 days.
                source_text = await self._resolve_definition_text_for_null_fi(entity_id, row)

            if not source_text:
                continue

            new_hash = sha256_hex(source_text)
            # Only skip re-embedding when hash matches AND an embedding already exists.
            # If embedding IS NULL (first-run row or COALESCE-preserved NULL), fall
            # through to needs_embed so the entity gets its first embedding.
            if new_hash == row.get("source_hash") and row.get("has_embedding"):
                # Unchanged — push next_refresh_at forward, keep existing embedding.
                unchanged.append(
                    _Update(
                        entity_id=entity_id,
                        source_text=source_text,
                        source_hash=new_hash,
                        embedding=None,  # COALESCE in SQL preserves existing
                        model_id=None,  # COALESCE in SQL preserves existing
                    ),
                )
                skipped += 1
                continue

            needs_embed.append((entity_id, source_text, new_hash))

        # Batch embed all changed entities in one (or a few) API calls.
        # Chunk by _EMBED_CHUNK_SIZE to stay within provider batch limits.
        embed_results: list[list[float] | None] = []
        if needs_embed:
            inputs_all = [EmbeddingInput(text=text, model_id=self._embed_model_id) for _, text, _ in needs_embed]
            for chunk_start in range(0, len(inputs_all), _EMBED_CHUNK_SIZE):
                chunk_inputs = inputs_all[chunk_start : chunk_start + _EMBED_CHUNK_SIZE]
                outputs = await self._llm.embed(chunk_inputs)
                for i in range(len(chunk_inputs)):
                    if outputs and i < len(outputs):
                        embed_results.append(outputs[i].embedding)
                    else:
                        embed_results.append(None)

        # Build the write list from batch embed results.
        to_write: list[_Update] = list(unchanged)
        refreshed = 0
        for (entity_id, source_text, new_hash), embedding in zip(needs_embed, embed_results, strict=False):
            if embedding is None:
                # Fallback exhausted; next_refresh_at unchanged → retry next cycle
                continue
            to_write.append(
                _Update(
                    entity_id=entity_id,
                    source_text=source_text,
                    source_hash=new_hash,
                    embedding=embedding,
                    model_id=self._embed_model_id,
                ),
            )
            refreshed += 1

        # ── Phase 3: Write ───────────────────────────────────────────────────
        if to_write:
            now = utc_now()  # type: ignore[no-any-return]
            async with self._sf() as session:
                emb_repo = EntityEmbeddingStateRepository(session)
                for item in to_write:
                    await emb_repo.upsert(
                        item.entity_id,
                        VIEW_DEFINITION,
                        embedding=item.embedding,
                        model_id=item.model_id,
                        source_text=item.source_text,
                        source_hash=item.source_hash,
                        next_refresh_at=now + timedelta(days=_REFRESH_INTERVAL_DAYS),  # type: ignore[operator]
                    )
                    # Write description text back to canonical_entities so graph
                    # node descriptions (and the S7 EntitySummary) are populated.
                    # Only write when source_text is present (skip if empty string).
                    if item.source_text:
                        await session.execute(
                            sa_text(
                                "UPDATE canonical_entities"
                                " SET description = :description, enriched_at = :enriched_at"
                                " WHERE entity_id = :entity_id"
                            ),
                            {
                                "description": item.source_text,
                                "enriched_at": now,
                                "entity_id": str(item.entity_id),
                            },
                        )
                await session.commit()

        logger.info(  # type: ignore[no-any-return]
            "definition_refresh_worker_complete",
            refreshed=refreshed,
            skipped_unchanged=skipped,
        )

    async def refresh_for_entity(
        self,
        entity_id: UUID,
        source_text: str,
        session_factory: async_sessionmaker[AsyncSession] | None = None,
    ) -> None:
        """Refresh definition embedding for a specific entity (consumer-triggered).

        Uses the worker's own session factory if no override provided.
        Change detection: skip if SHA-256 matches stored hash.
        """
        from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
            EntityEmbeddingStateRepository,
        )

        sf = session_factory or self._sf
        new_hash = sha256_hex(source_text)

        async with sf() as session:
            emb_repo = EntityEmbeddingStateRepository(session)
            existing = await emb_repo.get(entity_id, VIEW_DEFINITION)

            if existing and existing.get("source_hash") == new_hash:
                logger.debug(  # type: ignore[no-any-return]
                    "definition_refresh_skipped_unchanged",
                    entity_id=str(entity_id),
                )
                return

            embedding = await self._embed(entity_id, source_text)
            await emb_repo.upsert(
                entity_id,
                VIEW_DEFINITION,
                embedding=embedding,
                model_id=self._embed_model_id if embedding else None,
                source_text=source_text,
                source_hash=new_hash,
                next_refresh_at=utc_now() + timedelta(days=_REFRESH_INTERVAL_DAYS),  # type: ignore[no-any-return, operator]
            )
            await session.commit()

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    async def _resolve_non_company_text(
        self,
        entity_id: UUID,
        entity_type: str,
        row: dict[str, Any],
    ) -> str:
        """Generate a description for a non-company entity.

        Tries ``description_client.generate_description()`` first; falls back to
        a deterministic template when the client returns None (cost cap exceeded,
        API unavailable, or ``NullDescriptionAdapter`` in use).
        """
        canonical_name = str(row.get("canonical_name") or "")
        context_hints: dict[str, str] = {}
        if row.get("ticker"):
            context_hints["ticker"] = str(row["ticker"])
        if row.get("exchange"):
            context_hints["exchange"] = str(row["exchange"])
        if row.get("isin"):
            context_hints["isin"] = str(row["isin"])

        try:
            description = await self._description_client.generate_description(
                entity_id=str(entity_id),
                canonical_name=canonical_name,
                entity_type=entity_type,
                context_hints=context_hints,
            )
        except Exception as exc:
            logger.warning(  # type: ignore[no-any-return]
                "definition_refresh_description_error",
                entity_id=str(entity_id),
                entity_type=entity_type,
                error=str(exc),
            )
            description = None

        if description:
            return description

        # Deterministic fallback — always produces a non-empty string
        fallback = _fallback_description(canonical_name, entity_type)
        logger.debug(  # type: ignore[no-any-return]
            "definition_refresh_using_fallback_template",
            entity_id=str(entity_id),
            entity_type=entity_type,
        )
        return fallback

    async def _resolve_definition_text_for_null_fi(
        self,
        entity_id: UUID,
        row: dict[str, Any],
    ) -> str:
        """Generate a definition for a financial_instrument with NULL source_text.

        Used for crypto/FX/index instruments that EODHD has no business
        description for (RC2). Calls the description client (DeepInfra) and
        returns the generated text, or "" on any failure / empty result.

        Unlike ``_resolve_non_company_text`` this intentionally does NOT fall
        back to the deterministic ``"<name> is a financial_instrument."``
        template: a trivial template would be embedded and locked in for 90
        days, polluting semantic search. Returning "" makes the caller skip the
        row so it can be retried on the next cycle once the LLM recovers.

        BP-114 guard: a provider that silently returns an empty/whitespace
        string must NOT be persisted — we treat it the same as a failure.
        """
        canonical_name = str(row.get("canonical_name") or "")
        context_hints: dict[str, str] = {}
        if row.get("ticker"):
            context_hints["ticker"] = str(row["ticker"])
        if row.get("exchange"):
            context_hints["exchange"] = str(row["exchange"])
        if row.get("isin"):
            context_hints["isin"] = str(row["isin"])

        try:
            description = await self._description_client.generate_description(
                entity_id=str(entity_id),
                canonical_name=canonical_name,
                entity_type=_FINANCIAL_INSTRUMENT,
                context_hints=context_hints,
            )
        except Exception as exc:
            logger.warning(  # type: ignore[no-any-return]
                "definition_refresh_fi_null_description_error",
                entity_id=str(entity_id),
                ticker=context_hints.get("ticker"),
                error=str(exc),
            )
            return ""

        # BP-114: guard against a silent empty/whitespace return.
        if not description or not description.strip():
            logger.info(  # type: ignore[no-any-return]
                "definition_refresh_fi_null_description_empty",
                entity_id=str(entity_id),
                ticker=context_hints.get("ticker"),
            )
            return ""

        logger.info(  # type: ignore[no-any-return]
            "definition_refresh_fi_null_description_generated",
            entity_id=str(entity_id),
            ticker=context_hints.get("ticker"),
            chars=len(description),
        )
        return description

    async def _embed(self, entity_id: UUID, text: str) -> list[float] | None:
        from ml_clients.dataclasses import EmbeddingInput  # type: ignore[import-untyped]

        inp = EmbeddingInput(text=text, model_id=self._embed_model_id)
        outputs = await self._llm.embed([inp], entity_id=entity_id)
        if outputs is None or not outputs:
            return None
        return outputs[0].embedding
