"""Worker 13D-1: Definition embedding refresh (PRD §6.7 Block 13D-1 / PRD-0017 §6.5).

Triggered indirectly via consumers (market.instrument.created, market.dataset.fetched)
and also runs as a periodic fallback (quarterly — 90-day schedule).

For ``financial_instrument`` entities: source_text comes from EODHD (already stored).
For all other entity types: source_text is GENERATED by this worker each cycle using
``EntityDescriptionClient`` (gemini-3.1-flash-lite); falls back to a deterministic
template when the API is unavailable or cost cap exceeded.

Change detection: SHA-256(source_text) != source_hash → re-embed.
Uses FallbackChainClient: Ollama → Gemini Flash Lite → NULL + schedule retry.
UPSERT entity_embedding_state WHERE view_type='definition' with
next_refresh_at = now() + 90 days.
"""

from __future__ import annotations

import dataclasses
from datetime import timedelta
from typing import TYPE_CHECKING, Any

from common.time import utc_now  # type: ignore[import-untyped]
from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
    VIEW_DEFINITION,
    sha256_hex,
)
from observability import get_logger  # type: ignore[import-untyped]

if TYPE_CHECKING:
    from uuid import UUID

    from ml_clients.description_client import EntityDescriptionClient  # type: ignore[import-untyped]
    from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

    from knowledge_graph.infrastructure.llm.fallback_chain import FallbackChainClient

logger = get_logger(__name__)  # type: ignore[no-any-return]

_REFRESH_INTERVAL_DAYS = 90
_BATCH_LIMIT = 50
_EMBED_MODEL_ID = "nomic-embed-text"
_FINANCIAL_INSTRUMENT = "financial_instrument"


def _fallback_description(canonical_name: str, entity_type: str) -> str:
    """Deterministic description template — used when LLM is unavailable or cost-capped."""
    return f"{canonical_name} is a {entity_type}."


class DefinitionRefreshWorker:
    """Refreshes definition-view embeddings for entities (Worker 13D-1).

    For ``financial_instrument`` entities the description comes from EODHD data
    already stored as ``source_text``.  For all other entity types the worker
    generates a fresh world-knowledge description each cycle via
    ``description_client`` and falls back to a deterministic template on failure.

    Args:
        session_factory:    Read/write sessionmaker for intelligence_db.
        llm_client:         FallbackChainClient (embedding path).
        description_client: EntityDescriptionClient for non-company descriptions.
                            If None, ``NullDescriptionAdapter`` is used (always
                            returns None → falls back to deterministic template).
    """

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
        llm_client: FallbackChainClient,
        description_client: EntityDescriptionClient | None = None,
    ) -> None:
        self._sf = session_factory
        self._llm = llm_client
        if description_client is None:
            from ml_clients.description_client import NullDescriptionAdapter  # type: ignore[import-untyped]

            self._description_client: EntityDescriptionClient = NullDescriptionAdapter()
        else:
            self._description_client = description_client

    async def run(self) -> None:
        """Periodic fallback: refresh definition embeddings due for refresh.

        Execution is split into three phases to avoid holding a DB session
        across external I/O (HTTP description generation + ML embedding calls):

        Phase 1 — Read: fetch due rows, close session immediately.
        Phase 2 — Process: generate descriptions + embeddings (no session open).
        Phase 3 — Write: upsert all results in a single session + commit.
        """
        from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
            EntityEmbeddingStateRepository,
        )

        # ── Phase 1: Read ────────────────────────────────────────────────────
        async with self._sf() as session:
            emb_repo = EntityEmbeddingStateRepository(session)
            due = await emb_repo.get_due_for_refresh(VIEW_DEFINITION, _BATCH_LIMIT)
        # Session released here — FOR UPDATE lock released, that is acceptable
        # because this worker runs as a single periodic process.

        if not due:
            logger.info(  # type: ignore[no-any-return]
                "definition_refresh_worker_complete",
                refreshed=0,
                skipped_unchanged=0,
            )
            return

        # ── Phase 2: Process ─────────────────────────────────────────────────
        # No DB session open during description generation or embedding calls.
        refreshed = 0
        skipped = 0

        @dataclasses.dataclass
        class _Update:
            entity_id: UUID
            source_text: str
            source_hash: str
            embedding: list[float] | None
            model_id: str | None

        to_write: list[_Update] = []

        for row in due:
            entity_id: UUID = row["entity_id"]  # type: ignore[assignment]
            entity_type = str(row.get("entity_type") or "")
            source_text = str(row.get("source_text") or "")

            if entity_type != _FINANCIAL_INSTRUMENT:
                source_text = await self._resolve_non_company_text(entity_id, entity_type, row)

            if not source_text:
                continue

            new_hash = sha256_hex(source_text)
            if new_hash == row.get("source_hash"):
                # Unchanged — push next_refresh_at forward, keep existing embedding.
                to_write.append(
                    _Update(
                        entity_id=entity_id,
                        source_text=source_text,
                        source_hash=new_hash,
                        embedding=None,  # COALESCE in SQL preserves existing
                        model_id=None,  # COALESCE in SQL preserves existing
                    )
                )
                skipped += 1
                continue

            embedding = await self._embed(entity_id, source_text)
            if embedding is None:
                # Fallback exhausted; next_refresh_at unchanged → retry next cycle
                continue

            to_write.append(
                _Update(
                    entity_id=entity_id,
                    source_text=source_text,
                    source_hash=new_hash,
                    embedding=embedding,
                    model_id=_EMBED_MODEL_ID,
                )
            )
            refreshed += 1

        # ── Phase 3: Write ───────────────────────────────────────────────────
        if to_write:
            async with self._sf() as session:
                emb_repo = EntityEmbeddingStateRepository(session)
                for item in to_write:
                    await emb_repo.upsert(
                        item.entity_id,
                        VIEW_DEFINITION,
                        embedding=item.embedding,
                        model_id=item.model_id,
                        source_text=item.source_text,
                        source_hash=item.source_hash,
                        next_refresh_at=utc_now() + timedelta(days=_REFRESH_INTERVAL_DAYS),  # type: ignore[no-any-return, operator]
                    )
                await session.commit()

        logger.info(  # type: ignore[no-any-return]
            "definition_refresh_worker_complete",
            refreshed=refreshed,
            skipped_unchanged=skipped,
        )

    async def refresh_for_entity(
        self,
        entity_id: UUID,
        source_text: str,
        session_factory: async_sessionmaker[AsyncSession] | None = None,
    ) -> None:
        """Refresh definition embedding for a specific entity (consumer-triggered).

        Uses the worker's own session factory if no override provided.
        Change detection: skip if SHA-256 matches stored hash.
        """
        from knowledge_graph.infrastructure.intelligence_db.repositories.entity_embedding_state import (
            EntityEmbeddingStateRepository,
        )

        sf = session_factory or self._sf
        new_hash = sha256_hex(source_text)

        async with sf() as session:
            emb_repo = EntityEmbeddingStateRepository(session)
            existing = await emb_repo.get(entity_id, VIEW_DEFINITION)

            if existing and existing.get("source_hash") == new_hash:
                logger.debug(  # type: ignore[no-any-return]
                    "definition_refresh_skipped_unchanged",
                    entity_id=str(entity_id),
                )
                return

            embedding = await self._embed(entity_id, source_text)
            await emb_repo.upsert(
                entity_id,
                VIEW_DEFINITION,
                embedding=embedding,
                model_id=_EMBED_MODEL_ID if embedding else None,
                source_text=source_text,
                source_hash=new_hash,
                next_refresh_at=utc_now() + timedelta(days=_REFRESH_INTERVAL_DAYS),  # type: ignore[no-any-return, operator]
            )
            await session.commit()

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    async def _resolve_non_company_text(
        self,
        entity_id: UUID,
        entity_type: str,
        row: dict[str, Any],
    ) -> str:
        """Generate a description for a non-company entity.

        Tries ``description_client.generate_description()`` first; falls back to
        a deterministic template when the client returns None (cost cap exceeded,
        API unavailable, or ``NullDescriptionAdapter`` in use).
        """
        canonical_name = str(row.get("canonical_name") or "")
        context_hints: dict[str, str] = {}
        if row.get("ticker"):
            context_hints["ticker"] = str(row["ticker"])
        if row.get("exchange"):
            context_hints["exchange"] = str(row["exchange"])
        if row.get("isin"):
            context_hints["isin"] = str(row["isin"])

        try:
            description = await self._description_client.generate_description(
                entity_id=str(entity_id),
                canonical_name=canonical_name,
                entity_type=entity_type,
                context_hints=context_hints,
            )
        except Exception as exc:
            logger.warning(  # type: ignore[no-any-return]
                "definition_refresh_description_error",
                entity_id=str(entity_id),
                entity_type=entity_type,
                error=str(exc),
            )
            description = None

        if description:
            return description

        # Deterministic fallback — always produces a non-empty string
        fallback = _fallback_description(canonical_name, entity_type)
        logger.debug(  # type: ignore[no-any-return]
            "definition_refresh_using_fallback_template",
            entity_id=str(entity_id),
            entity_type=entity_type,
        )
        return fallback

    async def _embed(self, entity_id: UUID, text: str) -> list[float] | None:
        from ml_clients.dataclasses import EmbeddingInput  # type: ignore[import-untyped]

        inp = EmbeddingInput(text=text, model_id=_EMBED_MODEL_ID)
        outputs = await self._llm.embed([inp], entity_id=entity_id)
        if outputs is None or not outputs:
            return None
        return outputs[0].embedding
