[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
strict_equality = True
show_error_codes = True
pretty = True
mypy_path = ../../stubs
exclude = (?x)(^tests/|^alembic/)

[mypy-common]
ignore_missing_imports = True

[mypy-common.*]
ignore_missing_imports = True

[mypy-fastavro.*]
ignore_missing_imports = True

[mypy-minio.*]
ignore_missing_imports = True

[mypy-aiokafka.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-async_timeout.*]
ignore_missing_imports = True
